### ISSUE TITLE
sd webui 1.10.1 install error

### ISSUE THREAD

**Issue by skyliwq** [TheCodeSlinger/FacePop#2]
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

**Comment by TheCodeSlinger** [comment]
I've not tried it with a docker yet. I assume that's what you were using?

**Comment by skyliwq** [comment]
Yes, I use docker

**Comment by TheCodeSlinger** [comment]
I went through script.py, found nothing that should cause that error. Do you have any log? It's pretty much impossible to figure the issue without more information.

**Comment by skyliwq** [comment]
Error loading script: script.py
2024-09-24 10:07:19     Traceback (most recent call last):
2024-09-24 10:07:19       File "/app/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
2024-09-24 10:07:19         script_module = script_loading.load_module(scriptfile.path)
2024-09-24 10:07:19                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 10:07:19       File "/app/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
2024-09-24 10:07:19         module_spec.loader.exec_module(module)
2024-09-24 10:07:19       File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-09-24 10:07:19       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-09-24 10:07:19       File "/app/stable-diffusion-webui/extensions/sd-webui-facepop/scripts/script.py", line 22, in <module>
2024-09-24 10:07:19         mp_face_mesh = mp.solutions.face_mesh.FaceMesh(static_image_mode=True, max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.9)
2024-09-24 10:07:19                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 10:07:19       File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/python/solutions/face_mesh.py", line 95, in __init__
2024-09-24 10:07:19         super().__init__(
2024-09-24 10:07:19       File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/python/solution_base.py", line 248, in __init__
2024-09-24 10:07:19         self._graph = calculator_graph.CalculatorGraph(
2024-09-24 10:07:19                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24 10:07:19     RuntimeError: ValidatedGraphConfig Initialization failed.

**Comment by TheCodeSlinger** [comment]
I'm going to guess because you don't have mediapipe installed and my installer.py failed to include that. I've now updated the installer. Might check the new release 1.1.1. Also many other fixes besides that. Let me know if that fixes it or not. Thanks.

**Comment by skyliwq** [comment]
updated to the latest version, but still got an error

:17 *** Error loading script: script.py
2024-09-25 10:11:17     Traceback (most recent call last):
2024-09-25 10:11:17       File "/app/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
2024-09-25 10:11:17         script_module = script_loading.load_module(scriptfile.path)
2024-09-25 10:11:17                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 10:11:17       File "/app/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
2024-09-25 10:11:17         module_spec.loader.exec_module(module)
2024-09-25 10:11:17       File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-09-25 10:11:17       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-09-25 10:11:17       File "/app/stable-diffusion-webui/extensions/sd-webui-facepop/scripts/script.py", line 22, in <module>
2024-09-25 10:11:17         mp_face_mesh = mp.solutions.face_mesh.FaceMesh(static_image_mode=True, max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.9)
2024-09-25 10:11:17                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 10:11:17       File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/python/solutions/face_mesh.py", line 95, in __init__
2024-09-25 10:11:17         super().__init__(
2024-09-25 10:11:17       File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/python/solution_base.py", line 248, in __init__
2024-09-25 10:11:17         self._graph = calculator_graph.CalculatorGraph(
2024-09-25 10:11:17                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-25 10:11:17     RuntimeError: ValidatedGraphConfig Initialization failed.

**Comment by TheCodeSlinger** [comment]
hmmm now I'm thinking it's version of python and that's causing different than expected modules to import. Can you run it again using Python 3.10.6? I know I had to downgrade from 3.12 to this to get some of the mods working properly. And just curious is your docker able to support torch and tensors? Are you using a version of AUTOMATIC1111 that builds it's own venv?

Also I do appreciate your feedback and help. It's been about 11 years since I really used github last and it's kind of a learning curve getting back into things here again.

I have a series of features and updates as well as knocking out bugs and then plan to test it and get it ready for ForgeUI.
